// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAndroidSdkEnv() {
  return window['go']['app']['App']['GetAndroidSdkEnv']();
}

export function ListAVDs() {
  return window['go']['app']['App']['ListAVDs']();
}

export function ListRunningAVDs() {
  return window['go']['app']['App']['ListRunningAVDs']();
}

export function OpenEnvironmentVariables() {
  return window['go']['app']['App']['OpenEnvironmentVariables']();
}

export function StartAVD(arg1, arg2) {
  return window['go']['app']['App']['StartAVD'](arg1, arg2);
}

export function StopAVD(arg1) {
  return window['go']['app']['App']['StopAVD'](arg1);
}
